---
- name: Install service
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    version: "1.4"
    parentRole: elastichd
  loop:
    - pkgUrl: "https://github.com/360EntSecGroup-Skylar/ElasticHD/releases/download/{{ version }}/elasticHD_linux_amd64.zip"
      pkgType: zip
      extractArgs: []
      creates: ElasticHD
  loop_control:
    loop_var: opts

- name: install service
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
    - lib/systemd/system/
  loop_control:
    loop_var: file_path

- name: mask service
  systemd:
    name: elastichd
    enabled: no
    masked: yes
    state: stopped
