---
- name: install service
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    version: "{{ elkVersion }}.0"
    parentRole: elasticsearch-sql
  loop:
    - pkgUrl: "https://github.com/NLPchina/elasticsearch-sql/archive/{{ version }}.tar.gz"
      extractArgs: [ '--strip-components=2', '--exclude=assembly', '--exclude=main', '--exclude=test', '--exclude=features.md' ]
      creates: site-server
  loop_control:
    loop_var: opts

- name: install express lib
  npm:
    name: express
    path: "/opt/{{ role_name }}/current/site-server"

- name: enhance with pre-set cluster
  blockinfile:
    path: "/opt/{{ role_name }}/current/_site/index.html"
    insertbefore: "</head>"
    marker: "    <!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: '    <script src="init.js"></script>'

- name: install service
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
    - lib/systemd/system/
  loop_control:
    loop_var: file_path

- name: mask service
  systemd:
    name: "{{ role_name }}"
    enabled: no
    masked: yes
    state: stopped
