---
- name: Install service
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    version: f1b28e84151abddd178ce21b859ce33621cf5620
    parentRole: elasticsearch-head
  loop:
    - pkgUrl: "https://github.com/mobz/elasticsearch-head/archive/{{ version }}.tar.gz"
  loop_control:
    loop_var: opts

- name: install nodejs
  include_role:
    name: utils
    tasks_from: install-nodejs

- name: install dependencies
  vars:
    dir: "/opt/{{ role_name }}/current"
  shell: |
    npm install
    chown -R {{ role_name }}.svc {{ dir }}
  args:
    chdir: "{{ dir }}"
    creates: "{{ dir }}/node_modules"
    executable: /bin/bash

- name: Copy configuration files
  include_role:
    name: utils
    tasks_from: copy-conf
  vars:
    parentRole: elasticsearch-head

