---
- name: install service
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    version: 0.8.1
    parentRole: cerebro
  loop:
    - pkgUrl: "https://github.com/lmenezes/cerebro/releases/download/v{{ version }}/cerebro-{{ version }}.tgz"
  loop_control:
    loop_var: opts

- name: install tools
  apt:
    name: ['openjdk-8-jre']
    state: present
    update_cache: no

- name: copy configuration files
  include_role:
    name: utils
    tasks_from: copy-conf
  vars:
    parentRole: cerebro

