---
- name: set up var
  set_fact:
    userName: "{{ vm_user.username | d('ubuntu') }}"
    userPassword: "{{ vm_user.password | d(adminPwd) }}"

- name: set password
  user:
    name: ubuntu
    password: "{{ userPassword | password_hash('sha512') }}"
