---
- name: install ppa tools
  apt:
    name: ['software-properties-common']
    update_cache: no

- name: install ppa
  apt_repository:
    repo: ppa:vbernat/haproxy-1.8

- name: install HAProxy
  apt:
    name: haproxy=1.8.*
    state: present
    update_cache: yes

- name: disable haproxy auto start
  systemd:
    name: haproxy
    state: stopped
    enabled: no
    masked: yes

- name: copy logging conf files
  copy:
    src: roles/{{ role_name }}/files/{{ item }}
    dest: /{{ item }}
    owner: root
    group: root
    mode: u=rw,go=r
  with_items:
    - etc/haproxy/errors/
    - etc/logrotate.d/
    - etc/rsyslog.d/
