---
- name: install tools
  apt:
    name: ['unzip']
    state: present
    update_cache: no

- name: install binary
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    version: "{{ elk_version }}"
    parentRole: elasticsearch
  loop:
    - pkgUrl: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-{{ version }}-linux-x86_64.tar.gz"
  loop_control:
    loop_var: opts

- name: copy configuration files
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
  - opt/app/conf/elasticsearch/
  loop_control:
    loop_var: file_path

- name: install service
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
    - lib/systemd/system/
  loop_control:
    loop_var: file_path

- name: mask elasticsearch service
  systemd:
    name: elasticsearch
    enabled: no
    masked: yes
    state: stopped

- name: install plugins
  include_tasks: install-plugin.yml
  loop:
    - name: analysis-icu
    - name: analysis-ik
      url: "https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v{{ elk_version }}/elasticsearch-analysis-ik-{{ elk_version }}.zip"
    - name: analysis-kuromoji
    - name: analysis-phonetic
    - name: analysis-pinyin
      url: "https://github.com/medcl/elasticsearch-analysis-pinyin/releases/download/v{{ elk_version }}/elasticsearch-analysis-pinyin-{{ elk_version }}.zip"
    - name: ingest-attachment
    - name: mapper-murmur3
    - name: mapper-size
    - name: repository-hdfs
    - name: repository-s3
    - name: sql
      url: "https://github.com/NLPchina/elasticsearch-sql/releases/download/{{ elk_version }}.0/elasticsearch-sql-{{ elk_version }}.0.zip"
  loop_control:
    loop_var: opts

- name: prepare dict directory
  file:
    path: /opt/elasticsearch/current/plugins/analysis-ik/config/custom
    owner: root
    group: svc
    state: directory

- name: check if jieba dic exists
  stat:
    path: "{{ role_path }}/files/tmp/jieba.dic"
  register: jieba_dic
  delegate_to: localhost

- name: download jieba dict
  get_url:
    url: "https://github.com/QingCloudAppcenter/elk-archived/raw/master/docker-image/standard/elasticsearch/dicts/jieba.dic"
    dest: "{{ role_path }}/files/tmp/jieba.dic"
  delegate_to: localhost
  when: jieba_dic.stat.exists == False

- name: copy jieba dict
  copy:
    src: "{{ role_path }}/files/tmp/jieba.dic"
    dest: "/opt/elasticsearch/current/plugins/analysis-ik/config/custom/jieba.dic"
    owner: root
    group: svc
    mode: u=rw,go=r

- name: check if package file exists
  stat:
    path: "{{ role_path }}/files/tmp/extra_stopword.dic"
  register: stopword_dic
  delegate_to: localhost

- name: download dict for IKAnalyzer
  get_url:
    url: "https://github.com/QingCloudAppcenter/elk-archived/raw/master/docker-image/standard/elasticsearch/dicts/stop_words.dic"
    dest: "{{ role_path }}/files/tmp/extra_stopword.dic"
  delegate_to: localhost
  when: stopword_dic.stat.exists == False

- name: copy extra stopword dict
  copy:
    src: "{{ role_path }}/files/tmp/extra_stopword.dic"
    dest: "/opt/elasticsearch/current/plugins/analysis-ik/config/custom/extra_stopword.dic"
    owner: root
    group: svc
