---
- name: common setup
  hosts: all
  # strategy: free
  roles:
  - common
  - role: caddy-1.0.6
    vars:
      caddy_plugins: upload

- name: setup
  hosts: all
  strategy: free
  vars_files:
    - /root/.qcacode

  tasks:

  - include_role:
      name: "{{ svc_name }}"
    when: "'elasticsearch' in group_names"
    loop:
    - elasticsearch
    loop_control:
      loop_var: svc_name

  - include_role:
      name: "{{ svc_name }}"
    when: "'logstash' in group_names"
    loop:
    - logstash
    loop_control:
      loop_var: svc_name

  - include_role:
      name: "{{ svc_name }}"
    when: "'kibana' in group_names"
    loop:
    - kibana
    - cerebro
    - elastichd
    - elasticsearch-head
    - elasticsearch-hq
    - elasticsearch-sql
    - haproxy
    - keepalived
    loop_control:
      loop_var: svc_name

- name: Cleanup
  hosts: all
  strategy: free
  roles:
    - cleanup
