---
- name: Install pkg
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    version: "{{ elk_version }}"
    parentRole: kibana
  loop:
    - pkgUrl: "https://artifacts.elastic.co/downloads/kibana/kibana-oss-{{ version }}-linux-x86_64.tar.gz"
  loop_control:
    loop_var: opts

- name: copy configuration files
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
  - opt/app/conf/kibana/
  loop_control:
    loop_var: file_path

- name: install service
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
  - lib/systemd/system/
  loop_control:
    loop_var: file_path

- name: mask kibana service
  systemd:
    name: kibana
    enabled: no
    masked: yes
    state: stopped
