[template]
src = "elasticsearch-head.sh.tmpl"
dest = "/opt/app/bin/tmpl/elasticsearch-head.sh"
mode = "0700"
keys = [
  "/",
]
reload_cmd = "/opt/app/bin/tmpl/elasticsearch-head.sh; appctl reload elasticsearch-head"
