---
- name: set variables
  set_fact:
    ls_home: /usr/share/logstash

- name: install binaries
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    version: "{{ elkVersion }}"
    parentRole: logstash
    softLink: false
  loop:
    - pkgUrl: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ version }}.tar.gz"
  loop_control:
    loop_var: opts

- name: install 5.4.3 binaries
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    version: 5.4.3
    parentRole: logstash
    softLink: false
  loop:
    - pkgUrl: https://github.com/QingCloudAppcenter/elk/releases/download/1.2.8/logstash-5.4.3.tgz
  loop_control:
    loop_var: opts

- name: copy configuration files
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
  - opt/app/conf/logstash/
  loop_control:
    loop_var: file_path

- name: install service
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
  - lib/systemd/system/
  loop_control:
    loop_var: file_path

- name: mask logstash service
  systemd:
    name: logstash
    enabled: no
    masked: yes
    state: stopped

- name: create symbolic link
  file:
    src: /opt/logstash/{{ elkVersion }}
    dest: "{{ ls_home }}"
    owner: logstash
    group: logstash
    state: link

- name: add logstash bin dir to system-wide path
  copy:
    dest: /etc/profile.d/logstash-path.sh
    content: 'PATH=$PATH:{{ ls_home }}/bin'
