---
- name: set variables
  set_fact:
    ls_home: /usr/share/logstash

- name: install binaries
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    version: "{{ elkVersion }}"
    parentRole: logstash
  loop:
    - pkgUrl: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ version }}.tar.gz"
      svcHome: "{{ ls_home }}"
  loop_control:
    loop_var: opts

- name: Install plugins
  include_tasks: install-plugin.yml
  loop:
    - name: logstash-input-qingstor
      version: b4e6fd29ead81db27e06870573add00914b539b1
      url: https://github.com/yunify/logstash-input-qingstor/archive/b4e6fd29ead81db27e06870573add00914b539b1.zip
    - name: logstash-output-qingstor
      version: 0.3.6
      url: https://github.com/yunify/logstash-output-qingstor/archive/v0.3.6.zip
  loop_control:
    loop_var: opts

- name: copy configuration files
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
  - opt/app/conf/logstash/
  loop_control:
    loop_var: file_path

- name: install service
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
  - lib/systemd/system/
  loop_control:
    loop_var: file_path

- name: mask logstash service
  systemd:
    name: logstash
    enabled: no
    masked: yes
    state: stopped

- name: add logstash bin dir to system-wide path
  copy:
    dest: /etc/profile.d/logstash-path.sh
    content: 'PATH=$PATH:{{ ls_home }}/bin'
