---
- name: set variables
  set_fact:
    version: "3.5.0"

- name: install service
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    parentRole: elasticsearch-hq
    creates: applicaion.py
  loop:
    - pkgUrl: "https://github.com/ElasticHQ/elasticsearch-HQ/archive/v{{ version }}.tar.gz"
  loop_control:
    loop_var: opts

- name: install tools
  apt:
    name: ['python3-pip']
    state: present
    update_cache: no

- name: install dependencies
  vars:
    dir: "/opt/{{ role_name }}/current"
  pip:
    chdir: "{{ dir }}"
    requirements: "{{ dir }}/requirements.txt"

- name: fix permissions
  file:
    path: /opt/{{ role_name }}/{{ version }}
    owner: "{{ role_name }}"
    group: svc
    recurse: yes

- name: copy configuration files
  include_role:
    name: utils
    tasks_from: copy-conf
  vars:
    parentRole: elasticsearch-hq

